In [58]:
# basic libraries
import pandas as pd
import numpy as np

In [59]:
df = pd.read_csv("nfhs_distict_clean.csv")

# basic check
df.head()

,district,state,female_population_age_6_years_and_above_who_ever_attended_school_percent,children_under_age_5_years_whose_birth_was_registered_with_the_civil_authority_percent,deaths_in_the_last_3_years_registered_with_the_civil_authority_percent,population_living_in_households_with_electricity_percent,population_living_in_households_with_an_improved_drinking-water_source1_percent,population_living_in_households_that_use_an_improved_sanitation_facility2_percent,households_using_clean_fuel_for_cooking3_percent,households_using_iodized_salt_percent,households_with_any_usual_member_covered_under_a_health_insurance_financing_scheme_percent,children_age_5_years_who_attended_pre-primary_school_during_the_school_year_2019-20_percent,women_age_15-49_who_are_literate4_percent,women_age_15-49__with_10_or_more_years_of_schooling_percent,women_age_20-24_years_married_before_age_18_years_percent,births_in_the_5_years_preceding_the_survey_that_are_third_or_higher_order_percent,women_age_15-19_years_who_were_already_mothers_or_pregnant_at_the_time_of_the_survey_percent,women_age_15-24_years_who_use_hygienic_methods_of_protection_during_their_menstrual_period5_percent,current_use_of_family_planning_methods_currently_married_women_age_15-49__years_-_any_method6_percent,current_use_of_family_planning_methods_currently_married_women_age_15-49__years_-_any_modern_method6_percent,current_use_of_family_planning_methods_currently_married_women_age_15-49__years_-_female_sterilization_percent,current_use_of_family_planning_methods_currently_married_women_age_15-49__years_-_male_sterilization_percent,current_use_of_family_planning_methods_currently_married_women_age_15-49__years_-_iud_ppiud_percent,current_use_of_family_planning_methods_currently_married_women_age_15-49__years_-_pill_percent,current_use_of_family_planning_methods_currently_married_women_age_15-49__years_-_condom_percent,current_use_of_family_planning_methods_currently_married_women_age_15-49__years_-_injectables_percent,total_unmet_need_for_family_planning_currently_married_women_age_15-49__years7_percent,unmet_need_for_spacing_currently_married_women_age_15-49__years7_percent,health_worker_ever_talked_to_female_non-users_about_family_planning_percent,current_users_ever_told_about_side_effects_of_current_method_of_family_planning8_percent,mothers_who_had_an_antenatal_check-up_in_the_first_trimester__for_last_birth_in_the_5_years_before_the_survey_percent,mothers_who_had_at_least_4_antenatal_care_visits__for_last_birth_in_the_5_years_before_the_survey_percent,mothers_whose_last_birth_was_protected_against_neonatal_tetanus_for_last_birth_in_the_5_years_before_the_survey9_percent,mothers_who_consumed_iron_folic_acid_for_100_days_or_more_when_they_were_pregnant_for_last_birth_in_the_5_years_before_the_survey_percent,mothers_who_consumed_iron_folic_acid_for_180_days_or_more_when_they_were_pregnant_for_last_birth_in_the_5_years_before_the_survey}_percent,registered_pregnancies_for_which_the_mother_received_a_mother_and_child_protection_mcp_card_for_last_birth_in_the_5_years_before_the_survey_percent,mothers_who_received_postnatal_care_from_a_doctor_nurse_lhv_anm_midwife_other_health_personnel_within_2_days_of_delivery_for_last_birth_in_the_5_years_before_the_survey_percent,average_out-of-pocket_expenditure_per_delivery_in_a_public_health_facility_for_last_birth_in_the_5_years_before_the_survey_rs.,children_born_at_home_who_were_taken_to_a_health_facility_for_a_check-up_within_24_hours_of_birth_for_last_birth_in_the_5_years_before_the_survey}_percent,children_who_received_postnatal_care_from_a_doctor_nurse_lhv_anm_midwife__other_health_personnel_within_2_days_of_delivery_for_last_birth_in_the_5_years_before_the_survey_percent,institutional_births_in_the_5_years_before_the_survey_percent,institutional_births_in_public_facility_in_the_5_years_before_the_survey_percent,home_births_that_were_conducted_by_skilled_health_personnel__in_the_5_years_before_the_survey10_percent,births_attended_by_skilled_health_personnel_in_the_5_years_before_the_survey10_percent,births_delivered_by_caesarean_section_in_the_5_years_before_the_survey_percent,births_in_a_private_health_facility_that_were_delivered_by_caesarean_section_in_the_5_years_before_the_survey_percent,births_in_a_public_health_facility_that_were_delivered_by_caesarean_section_in_the_5_years_before_the_survey_percent,children_age_12-23_months_fully_vaccinated_based_on_information_from_either_vaccination_card_or_mother's_recall11_percent,children_age_12-23_months_fully_vaccinated_based_on_information_from_vaccination_card_only12_percent,children_age_12-23_months_who_have_received_bcg_percent,children_age_12-23_months_who_have_received_3_doses_of_polio_vaccine13_percent,children_age_12-23_months_who_have_received_3_doses_of_penta_or_dpt_vaccine_percent,children_age_12-23_months_who_have_received_the_first_dose_of_measles-containing_vaccine_mcv_percent,children_age_24-35_months_who_have_received_a_second_dose_of_measles-containing_vaccine_mcv_percent,children_age_12-23_months_who_have_received_3_doses_of_rotavirus_vaccine14_percent,children_age_12-23_months_who_have_received_3_doses_of_penta_or_hepatitis_b_vaccine_percent,children_age_9-35_months_who_received_a_vitamin_a_dose_in_the_last_6_months_percent,children_age_12-23_months_who_received_most_of_their_vaccinations_in_a_public_health_facility_percent,children_age_12-23_months_who_received_most_of_their_vaccinations_in_a_private_health_facility_percent,prevalence_of_diarrhoea_in_the_2_weeks_preceding_the_survey_children_under_age_5_years_percent,children_with_diarrhoea_in_the_2_weeks_preceding_the_survey_who_received_oral_rehydration_salts_ors_children_under_age_5_years_percent,children_with_diarrhoea_in_the_2_weeks_preceding_the_survey_who_received_zinc_children_under_age_5_years_percent,children_swith_diarrhoea_in_the_2_weeks_preceding_the_survey_taken_to_a_health_facility_or_health_provider_children_under_age_5_years_percent,children_prevalence_of_symptoms_of_acute_respiratory_infection_ari_in_the_2_weeks_preceding_the_survey_children_under_age_5_years_percent,children_with_fever_or_symptoms_of_ari_in_the_2_weeks_preceding_the_survey_taken_to_a_health_facility_or_health_provider_children_under_age_5_years_percent,children_under_age_3_years_breastfed_within_one_hour_of_birth15_percent,children_under_age_6_months_exclusively_breastfed16_percent,children_age_6-8_months_receiving_solid_or_semi-solid_food_and_breastmilk16_percent,"breastfeeding_children_age_6-23_months_receiving_an_adequate_diet16,_17__percent","non-breastfeeding_children_age_6-23_months_receiving_an_adequate_diet16,_17_percent","total_children_age_6-23_months_receiving_an_adequate_diet16,_17__percent",children_under_5_years_who_are_stunted_height-for-age18_percent,children_under_5_years_who_are_wasted_weight-for-height18_percent,children_under_5_years_who_are_severely_wasted_weight-for-height19_percent,children_under_5_years_who_are_underweight_weight-for-age18_percent,children_under_5_years_who_are_overweight_weight-for-height20_percent,women_age_15-49_years_whose_body_mass_index_bmi_is_below_normal_bmi_<18.5_kg_m221_percent,women_age_15-49_years_who_are_overweight_or_obese_bmi_≥25.0_kg_m221_percent,women_age_15-49_years_who_have_high_risk_waist-to-hip_ratio_≥0.85_percent,children_age_6-59_months_who_are_anaemic_<11.0_g_dl22_percent,non-pregnant_women_age_15-49_years_who_are_anaemic_<12.0_g_dl22_percent,pregnant_women_age_15-49_years_who_are_anaemic_<11.0_g_dl22_percent,all_women_age_15-49_years_who_are_anaemic22_percent,all_women_age_15-19_years_who_are_anaemic22_percent,women__age_15_years_and_above_with_high_141-160_mg_dl_blood_sugar_level23_percent,women_age_15_years_and_above_wih_very_high_>160_mg_dl_blood_sugar_level23_percent,women_age_15_years_and_above_wih_high_or_very_high_>140_mg_dl_blood_sugar_level_or_taking_medicine_to_control_blood_sugar_level23_percent,men_age_15_years_and_above_wih_high_141-160_mg_dl_blood_sugar_level23_percent,men_age_15_years_and_above_wih__very_high_>160_mg_dl_blood_sugar_level23_percent,men_age_15_years_and_above_wih_high_or_very_high_>140_mg_dl_blood_sugar_level__or_taking_medicine_to_control_blood_sugar_level23_percent,women_age_15_years_and_above_wih_mildly_elevated_blood_pressure_systolic_140-159_mm_of_hg_and_or_diastolic_90-99_mm_of_hg_percent,women_age_15_years_and_above_wih_moderately_or_severely_elevated_blood_pressure_systolic_≥160_mm_of_hg_and_or_diastolic_≥100_mm_of_hg_percent,women_age_15_years_and_above_wih_elevated_blood_pressure_systolic_≥140_mm_of_hg_and_or_diastolic_≥90_mm_of_hg_or_taking_medicine_to_control_blood_pressure_percent,men_age_15_years_and_above_wih_mildly_elevated_blood_pressure_systolic_140-159_mm_of_hg_and_or_diastolic_90-99_mm_of_hg_percent,men_age_15_years_and_above_wih_moderately_or_severely_elevated_blood_pressure_systolic_≥160_mm_of_hg_and_or_diastolic_≥100_mm_of_hg_percent,men_age_15_years_and_above_wih_elevated_blood_pressure_systolic_≥140_mm_of_hg_and_or_diastolic_≥90_mm_of_hg_or_taking_medicine_to_control_blood_pressure_percent,women_age_30-49_years_ever_undergone_a_screening_test_for_cervical_cancer_percent,women_age_30-49_years_ever_undergone_a_breast_examination_for_breast_cancer_percent,women_age_30-49_years_ever_undergone_an_oral_cavity_examination_for_oral_cancer_percent,women_age_15_years_and_above_who_use_any_kind_of_tobacco_percent,men_age_15_years_and_above_who_use_any_kind_of_tobacco_percent,women_age_15_years_and_above_who_consume_alcohol_percent,men_age_15_years_and_above_who_consume_alcohol_percent
0,nicobars,andaman and nicobar islands,78.0,98.0,83.2,97.9,98.8,83.5,56.9,99.4,2.7,(29.5),87.5,53.5,11.4,0.0,1.8,100.0,65.3,57.2,46.4,0.0,2.7,2.0,4.9,1.2,9.5,3.3,40.4,49.4,62.8,71.7,78.0,72.6,43.9,97.9,85.1,2278,*,92.5,97.8,96.7,0.8,98.6,11.5,*,10.7,(64.2),(94.1),(80.4),(69.1),(71.9),(67.3),(20.7),(3.1),(68.6),94.9,(100.0),(0.0),5.7,*,*,*,1.8,(85.7),55.4,*,*,(19.4),*,(18.7),21.6,15.7,7.8,24.6,1.5,8.2,39.1,62.5,37.7,38.4,*,38.3,48.0,7.4,3.9,13.1,9.6,4.4,15.4,23.2,8.5,35.4,32.9,11.1,47.0,13.4,13.2,5.4,63.5,76.8,29.6,64.5
1,north and middle andaman,andaman and nicobar islands,82.7,100.0,(92.6),93.2,92.2,86.4,61.3,99.9,2.1,(30.1),84.0,41.0,15.4,1.5,3.8,100.0,84.1,73.1,48.3,0.6,6.4,7.8,9.3,0.0,5.8,1.3,23.2,83.2,74.5,79.2,91.1,83.7,24.1,99.2,92.5,1904,*,94.3,97.7,95.0,0.7,98.3,12.9,*,11.4,*,*,*,*,*,*,*,*,*,(89.6),*,*,4.5,*,*,*,7.0,*,27.3,*,*,(6.5),*,(5.9),27.0,27.0,8.3,42.8,0.8,8.6,35.9,79.3,30.4,62.5,*,62.1,47.8,7.2,6.4,16.7,9.1,6.9,18.3,18.4,4.0,27.4,22.6,6.0,32.2,1.7,0.3,15.8,46.8,70.5,5.1,45.3
2,south andaman,andaman and nicobar islands,84.7,96.5,92.2,99.6,97.9,89.3,91.9,99.7,1.2,(50.8),86.7,57.5,17.1,0.5,2.8,98.2,57.1,50.5,34.0,0.0,2.8,1.8,10.6,0.3,17.6,8.6,31.2,88.2,79.4,85.9,92.1,81.0,61.9,98.9,88.1,3460,*,89.8,99.5,83.8,0.0,96.9,37.1,(79.1),29.6,(76.3),(96.6),(100.0),(79.0),(94.8),(81.7),(33.7),(0.0),(85.3),84.0,(93.1),(4.3),6.0,*,*,*,0.0,(77.3),51.1,*,*,(22.3),*,23.5,21.1,12.6,3.5,17.4,7.2,10.0,39.0,78.2,43.4,57.6,*,57.7,43.2,7.5,9.5,18.4,9.3,7.8,18.1,12.7,4.9,23.0,17.9,6.1,26.9,1.3,0.7,8.0,19.6,50.8,1.7,32.8
3,srikakulam,andhra pradesh,60.0,95.0,71.0,99.9,87.7,71.6,74.7,76.5,75.6,(0.0),64.3,42.5,25.4,0.0,5.5,78.0,72.3,72.2,71.0,0.3,0.6,0.0,0.3,0.0,5.7,3.6,16.0,45.8,79.7,78.4,94.4,67.5,35.3,100.0,90.8,3479,*,97.7,97.9,52.2,0.5,96.4,57.0,73.8,44.5,(82.8),(100.0),(93.3),(82.8),(89.7),(93.3),(34.9),(74.8),(89.7),69.6,(97.0),(3.0),11.9,*,*,*,1.3,(79.7),42.8,*,*,(14.0),*,16.1,19.7,19.5,7.4,21.4,4.5,13.8,27.2,54.0,59.6,62.8,*,62.6,59.2,8.2,7.8,17.4,6.8,8.6,17.6,12.8,5.9,22.1,14.4,5.5,22.9,1.0,0.2,3.8,7.1,21.3,0.6,28.3
4,vizianagaram,andhra pradesh,56.0,95.4,81.7,99.5,93.1,61.7,60.3,85.0,76.7,(25.2),58.3,37.6,33.7,2.2,12.7,72.5,71.2,71.2,69.3,1.3,0.0,0.0,0.6,0.0,6.7,4.7,21.1,36.4,76.1,71.4,91.3,59.6,32.4,98.8,83.9,1931,*,89.2,99.0,70.6,0.5,97.6,41.3,70.3,30.3,(76.8),*,(100.0),(76.8),(90.3),(92.5),(35.0),(77.3),(83.6),85.9,(100.0),(0.0),7.5,*,*,*,1.4,(83.5),55.6,*,*,(2.5),*,1.8,36.4,19.2,8.3,32.2,4.7,16.9,28.8,58.0,66.7,64.6,*,64.0,73.9,6.2,7.0,14.3,5.8,7.5,14.5,12.9,6.6,25.2,14.8,6.4,25.1,4.9,0.6,7.3,11.4,21.5,0.8,32.3

In [60]:
print("Shape:", df.shape)

Shape: (707, 103)

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 707 entries, 0 to 706
Columns: 103 entries, district to men_age_15_years_and_above_who_consume_alcohol_percent
dtypes: float64(53), object(50)
memory usage: 569.0+ KB

In [62]:
df.columns

Index(['district', 'state',
       'female_population_age_6_years_and_above_who_ever_attended_school_percent',
       'children_under_age_5_years_whose_birth_was_registered_with_the_civil_authority_percent',
       'deaths_in_the_last_3_years_registered_with_the_civil_authority_percent',
       'population_living_in_households_with_electricity_percent',
       'population_living_in_households_with_an_improved_drinking-water_source1_percent',
       'population_living_in_households_that_use_an_improved_sanitation_facility2_percent',
       'households_using_clean_fuel_for_cooking3_percent',
       'households_using_iodized_salt_percent',
       ...
       'men_age_15_years_and_above_wih_mildly_elevated_blood_pressure_systolic_140-159_mm_of_hg_and_or_diastolic_90-99_mm_of_hg_percent',
       'men_age_15_years_and_above_wih_moderately_or_severely_elevated_blood_pressure_systolic_≥160_mm_of_hg_and_or_diastolic_≥100_mm_of_hg_percent',
       'men_age_15_years_and_above_wih_elevated_blood_pressure_systolic_≥140_mm_of_hg_and_or_diastolic_≥90_mm_of_hg_or_taking_medicine_to_control_blood_pressure_percent',
       'women_age_30-49_years_ever_undergone_a_screening_test_for_cervical_cancer_percent',
       'women_age_30-49_years_ever_undergone_a_breast_examination_for_breast_cancer_percent',
       'women_age_30-49_years_ever_undergone_an_oral_cavity_examination_for_oral_cancer_percent',
       'women_age_15_years_and_above_who_use_any_kind_of_tobacco_percent',
       'men_age_15_years_and_above_who_use_any_kind_of_tobacco_percent',
       'women_age_15_years_and_above_who_consume_alcohol_percent',
       'men_age_15_years_and_above_who_consume_alcohol_percent'],
      dtype='object', length=103)

In [63]:
df.columns = df.columns.str.lower().str.replace(" ", "_")

In [64]:
# show ALL columns (no limit)
pd.set_option('display.max_columns', None)

# optional: column width bhi full dikhe
pd.set_option('display.max_colwidth', None)

# ab print karo
print(df.columns)

Index(['district', 'state',
       'female_population_age_6_years_and_above_who_ever_attended_school_percent',
       'children_under_age_5_years_whose_birth_was_registered_with_the_civil_authority_percent',
       'deaths_in_the_last_3_years_registered_with_the_civil_authority_percent',
       'population_living_in_households_with_electricity_percent',
       'population_living_in_households_with_an_improved_drinking-water_source1_percent',
       'population_living_in_households_that_use_an_improved_sanitation_facility2_percent',
       'households_using_clean_fuel_for_cooking3_percent',
       'households_using_iodized_salt_percent',
       ...
       'men_age_15_years_and_above_wih_mildly_elevated_blood_pressure_systolic_140-159_mm_of_hg_and_or_diastolic_90-99_mm_of_hg_percent',
       'men_age_15_years_and_above_wih_moderately_or_severely_elevated_blood_pressure_systolic_≥160_mm_of_hg_and_or_diastolic_≥100_mm_of_hg_percent',
       'men_age_15_years_and_above_wih_elevated_blood_pressure_systolic_≥140_mm_of_hg_and_or_diastolic_≥90_mm_of_hg_or_taking_medicine_to_control_blood_pressure_percent',
       'women_age_30-49_years_ever_undergone_a_screening_test_for_cervical_cancer_percent',
       'women_age_30-49_years_ever_undergone_a_breast_examination_for_breast_cancer_percent',
       'women_age_30-49_years_ever_undergone_an_oral_cavity_examination_for_oral_cancer_percent',
       'women_age_15_years_and_above_who_use_any_kind_of_tobacco_percent',
       'men_age_15_years_and_above_who_use_any_kind_of_tobacco_percent',
       'women_age_15_years_and_above_who_consume_alcohol_percent',
       'men_age_15_years_and_above_who_consume_alcohol_percent'],
      dtype='object', length=103)

In [65]:
for col in df.columns:
    print(col)

district
state
female_population_age_6_years_and_above_who_ever_attended_school_percent
children_under_age_5_years_whose_birth_was_registered_with_the_civil_authority_percent
deaths_in_the_last_3_years_registered_with_the_civil_authority_percent
population_living_in_households_with_electricity_percent
population_living_in_households_with_an_improved_drinking-water_source1_percent
population_living_in_households_that_use_an_improved_sanitation_facility2_percent
households_using_clean_fuel_for_cooking3_percent
households_using_iodized_salt_percent
households_with_any_usual_member_covered_under_a_health_insurance_financing_scheme_percent
children_age_5_years_who_attended_pre-primary_school_during_the_school_year_2019-20_percent
women_age_15-49_who_are_literate4_percent
women_age_15-49__with_10_or_more_years_of_schooling_percent
women_age_20-24_years_married_before_age_18_years_percent
births_in_the_5_years_preceding_the_survey_that_are_third_or_higher_order_percent
women_age_15-19_years_who_were_already_mothers_or_pregnant_at_the_time_of_the_survey_percent
women_age_15-24_years_who_use_hygienic_methods_of_protection_during_their_menstrual_period5_percent
current_use_of_family_planning_methods_currently_married_women_age_15-49__years_-_any_method6_percent
current_use_of_family_planning_methods_currently_married_women_age_15-49__years_-_any_modern_method6_percent
current_use_of_family_planning_methods_currently_married_women_age_15-49__years_-_female_sterilization_percent
current_use_of_family_planning_methods_currently_married_women_age_15-49__years_-_male_sterilization_percent
current_use_of_family_planning_methods_currently_married_women_age_15-49__years_-_iud_ppiud_percent
current_use_of_family_planning_methods_currently_married_women_age_15-49__years_-_pill_percent
current_use_of_family_planning_methods_currently_married_women_age_15-49__years_-_condom_percent
current_use_of_family_planning_methods_currently_married_women_age_15-49__years_-_injectables_percent
total_unmet_need_for_family_planning_currently_married_women_age_15-49__years7_percent
unmet_need_for_spacing_currently_married_women_age_15-49__years7_percent
health_worker_ever_talked_to_female_non-users_about_family_planning_percent
current_users_ever_told_about_side_effects_of_current_method_of_family_planning8_percent
mothers_who_had_an_antenatal_check-up_in_the_first_trimester__for_last_birth_in_the_5_years_before_the_survey_percent
mothers_who_had_at_least_4_antenatal_care_visits__for_last_birth_in_the_5_years_before_the_survey_percent
mothers_whose_last_birth_was_protected_against_neonatal_tetanus_for_last_birth_in_the_5_years_before_the_survey9_percent
mothers_who_consumed_iron_folic_acid_for_100_days_or_more_when_they_were_pregnant_for_last_birth_in_the_5_years_before_the_survey_percent
mothers_who_consumed_iron_folic_acid_for_180_days_or_more_when_they_were_pregnant_for_last_birth_in_the_5_years_before_the_survey}_percent
registered_pregnancies_for_which_the_mother_received_a_mother_and_child_protection_mcp_card_for_last_birth_in_the_5_years_before_the_survey_percent
mothers_who_received_postnatal_care_from_a_doctor_nurse_lhv_anm_midwife_other_health_personnel_within_2_days_of_delivery_for_last_birth_in_the_5_years_before_the_survey_percent
average_out-of-pocket_expenditure_per_delivery_in_a_public_health_facility_for_last_birth_in_the_5_years_before_the_survey_rs.
children_born_at_home_who_were_taken_to_a_health_facility_for_a_check-up_within_24_hours_of_birth_for_last_birth_in_the_5_years_before_the_survey}_percent
children_who_received_postnatal_care_from_a_doctor_nurse_lhv_anm_midwife__other_health_personnel_within_2_days_of_delivery_for_last_birth_in_the_5_years_before_the_survey_percent
institutional_births_in_the_5_years_before_the_survey_percent
institutional_births_in_public_facility_in_the_5_years_before_the_survey_percent
home_births_that_were_conducted_by_skilled_health_personnel__in_the_5_years_before_the_survey10_percent
births_attended_by_skilled_health_personnel_in_the_5_years_before_the_survey10_percent
births_delivered_by_caesarean_section_in_the_5_years_before_the_survey_percent
births_in_a_private_health_facility_that_were_delivered_by_caesarean_section_in_the_5_years_before_the_survey_percent
births_in_a_public_health_facility_that_were_delivered_by_caesarean_section_in_the_5_years_before_the_survey_percent
children_age_12-23_months_fully_vaccinated_based_on_information_from_either_vaccination_card_or_mother's_recall11_percent
children_age_12-23_months_fully_vaccinated_based_on_information_from_vaccination_card_only12_percent
children_age_12-23_months_who_have_received_bcg_percent
children_age_12-23_months_who_have_received_3_doses_of_polio_vaccine13_percent
children_age_12-23_months_who_have_received_3_doses_of_penta_or_dpt_vaccine_percent
children_age_12-23_months_who_have_received_the_first_dose_of_measles-containing_vaccine_mcv_percent
children_age_24-35_months_who_have_received_a_second_dose_of_measles-containing_vaccine_mcv_percent
children_age_12-23_months_who_have_received_3_doses_of_rotavirus_vaccine14_percent
children_age_12-23_months_who_have_received_3_doses_of_penta_or_hepatitis_b_vaccine_percent
children_age_9-35_months_who_received_a_vitamin_a_dose_in_the_last_6_months_percent
children_age_12-23_months_who_received_most_of_their_vaccinations_in_a_public_health_facility_percent
children_age_12-23_months_who_received_most_of_their_vaccinations_in_a_private_health_facility_percent
prevalence_of_diarrhoea_in_the_2_weeks_preceding_the_survey_children_under_age_5_years_percent
children_with_diarrhoea_in_the_2_weeks_preceding_the_survey_who_received_oral_rehydration_salts_ors_children_under_age_5_years_percent
children_with_diarrhoea_in_the_2_weeks_preceding_the_survey_who_received_zinc_children_under_age_5_years_percent
children_swith_diarrhoea_in_the_2_weeks_preceding_the_survey_taken_to_a_health_facility_or_health_provider_children_under_age_5_years_percent
children_prevalence_of_symptoms_of_acute_respiratory_infection_ari_in_the_2_weeks_preceding_the_survey_children_under_age_5_years_percent
children_with_fever_or_symptoms_of_ari_in_the_2_weeks_preceding_the_survey_taken_to_a_health_facility_or_health_provider_children_under_age_5_years_percent
children_under_age_3_years_breastfed_within_one_hour_of_birth15_percent
children_under_age_6_months_exclusively_breastfed16_percent
children_age_6-8_months_receiving_solid_or_semi-solid_food_and_breastmilk16_percent
breastfeeding_children_age_6-23_months_receiving_an_adequate_diet16,_17__percent
non-breastfeeding_children_age_6-23_months_receiving_an_adequate_diet16,_17_percent
total_children_age_6-23_months_receiving_an_adequate_diet16,_17__percent
children_under_5_years_who_are_stunted_height-for-age18_percent
children_under_5_years_who_are_wasted_weight-for-height18_percent
children_under_5_years_who_are_severely_wasted_weight-for-height19_percent
children_under_5_years_who_are_underweight_weight-for-age18_percent
children_under_5_years_who_are_overweight_weight-for-height20_percent
women_age_15-49_years_whose_body_mass_index_bmi_is_below_normal_bmi_<18.5_kg_m221_percent
women_age_15-49_years_who_are_overweight_or_obese_bmi_≥25.0_kg_m221_percent
women_age_15-49_years_who_have_high_risk_waist-to-hip_ratio_≥0.85_percent
children_age_6-59_months_who_are_anaemic_<11.0_g_dl22_percent
non-pregnant_women_age_15-49_years_who_are_anaemic_<12.0_g_dl22_percent
pregnant_women_age_15-49_years_who_are_anaemic_<11.0_g_dl22_percent
all_women_age_15-49_years_who_are_anaemic22_percent
all_women_age_15-19_years_who_are_anaemic22_percent
women__age_15_years_and_above_with_high_141-160_mg_dl_blood_sugar_level23_percent
women_age_15_years_and_above_wih_very_high_>160_mg_dl_blood_sugar_level23_percent
women_age_15_years_and_above_wih_high_or_very_high_>140_mg_dl_blood_sugar_level_or_taking_medicine_to_control_blood_sugar_level23_percent
men_age_15_years_and_above_wih_high_141-160_mg_dl_blood_sugar_level23_percent
men_age_15_years_and_above_wih__very_high_>160_mg_dl_blood_sugar_level23_percent
men_age_15_years_and_above_wih_high_or_very_high_>140_mg_dl_blood_sugar_level__or_taking_medicine_to_control_blood_sugar_level23_percent
women_age_15_years_and_above_wih_mildly_elevated_blood_pressure_systolic_140-159_mm_of_hg_and_or_diastolic_90-99_mm_of_hg_percent
women_age_15_years_and_above_wih_moderately_or_severely_elevated_blood_pressure_systolic_≥160_mm_of_hg_and_or_diastolic_≥100_mm_of_hg_percent
women_age_15_years_and_above_wih_elevated_blood_pressure_systolic_≥140_mm_of_hg_and_or_diastolic_≥90_mm_of_hg_or_taking_medicine_to_control_blood_pressure_percent
men_age_15_years_and_above_wih_mildly_elevated_blood_pressure_systolic_140-159_mm_of_hg_and_or_diastolic_90-99_mm_of_hg_percent
men_age_15_years_and_above_wih_moderately_or_severely_elevated_blood_pressure_systolic_≥160_mm_of_hg_and_or_diastolic_≥100_mm_of_hg_percent
men_age_15_years_and_above_wih_elevated_blood_pressure_systolic_≥140_mm_of_hg_and_or_diastolic_≥90_mm_of_hg_or_taking_medicine_to_control_blood_pressure_percent
women_age_30-49_years_ever_undergone_a_screening_test_for_cervical_cancer_percent
women_age_30-49_years_ever_undergone_a_breast_examination_for_breast_cancer_percent
women_age_30-49_years_ever_undergone_an_oral_cavity_examination_for_oral_cancer_percent
women_age_15_years_and_above_who_use_any_kind_of_tobacco_percent
men_age_15_years_and_above_who_use_any_kind_of_tobacco_percent
women_age_15_years_and_above_who_consume_alcohol_percent
men_age_15_years_and_above_who_consume_alcohol_percent

In [66]:
df.columns = df.columns.str.lower().str.replace(" ", "_")

In [67]:
df.rename(columns={

#  Nutrition
'children_under_5_years_who_are_stunted_height-for-age18_percent': 'child_stunting_rate',

'children_under_5_years_who_are_wasted_weight-for-height18_percent': 'child_wasting_rate',

'children_under_5_years_who_are_underweight_weight-for-age18_percent': 'child_underweight_rate',

#  Anemia
'children_age_6-59_months_who_are_anaemic_<11.0_g_dl22_percent': 'child_anemia_rate',

'all_women_age_15-49_years_who_are_anaemic22_percent': 'women_anemia_rate',

#  Disease
'prevalence_of_diarrhoea_in_the_2_weeks_preceding_the_survey_children_under_age_5_years_percent': 'child_diarrhea_rate',

'children_prevalence_of_symptoms_of_acute_respiratory_infection_ari_in_the_2_weeks_preceding_the_survey_children_under_age_5_years_percent': 'child_ari_rate',

#  Infrastructure
'population_living_in_households_with_an_improved_drinking-water_source1_percent': 'safe_drinking_water_access',

'population_living_in_households_that_use_an_improved_sanitation_facility2_percent': 'sanitation_access',

'population_living_in_households_with_electricity_percent': 'electricity_access',

'households_using_clean_fuel_for_cooking3_percent': 'clean_cooking_fuel_access',

#  Nutrition Support
'households_using_iodized_salt_percent': 'iodized_salt_usage',

#  Healthcare
'institutional_births_in_the_5_years_before_the_survey_percent': 'institutional_delivery_rate',

'children_age_12-23_months_fully_vaccinated_based_on_information_from_either_vaccination_card_or_mother\'s_recall11_percent': 'full_immunization_rate',

'households_with_any_usual_member_covered_under_a_health_insurance_financing_scheme_percent': 'health_insurance_coverage',

#  Lifestyle
'women_age_15_years_and_above_who_use_any_kind_of_tobacco_percent': 'tobacco_use_women',

'men_age_15_years_and_above_who_use_any_kind_of_tobacco_percent': 'tobacco_use_men',

'women_age_15_years_and_above_who_consume_alcohol_percent': 'alcohol_use_women',

'men_age_15_years_and_above_who_consume_alcohol_percent': 'alcohol_use_men',

#  NCD
'women_age_15_years_and_above_wih_high_or_very_high_>140_mg_dl_blood_sugar_level_or_taking_medicine_to_control_blood_sugar_level23_percent': 'high_blood_sugar_women',

'men_age_15_years_and_above_wih_high_or_very_high_>140_mg_dl_blood_sugar_level__or_taking_medicine_to_control_blood_sugar_level23_percent': 'high_blood_sugar_men',

'women_age_15_years_and_above_wih_elevated_blood_pressure_systolic_≥140_mm_of_hg_and_or_diastolic_≥90_mm_of_hg_or_taking_medicine_to_control_blood_pressure_percent': 'high_blood_pressure_women',

'men_age_15_years_and_above_wih_elevated_blood_pressure_systolic_≥140_mm_of_hg_and_or_diastolic_≥90_mm_of_hg_or_taking_medicine_to_control_blood_pressure_percent': 'high_blood_pressure_men',

#  Awareness
'female_population_age_6_years_and_above_who_ever_attended_school_percent': 'female_education_rate'

}, inplace=True)

In [68]:
final_columns = [

'district',
'state',

'child_stunting_rate',
'child_wasting_rate',
'child_underweight_rate',

'child_anemia_rate',
'women_anemia_rate',

'child_diarrhea_rate',
'child_ari_rate',

'safe_drinking_water_access',
'sanitation_access',
'electricity_access',
'clean_cooking_fuel_access',

'iodized_salt_usage',

'institutional_delivery_rate',
'full_immunization_rate',
'health_insurance_coverage',

'tobacco_use_women',
'tobacco_use_men',
'alcohol_use_women',
'alcohol_use_men',

'high_blood_sugar_women',
'high_blood_sugar_men',

'high_blood_pressure_women',
'high_blood_pressure_men',

'female_education_rate'
]

In [69]:
df = df[final_columns]

In [70]:
print(df.shape)

(707, 26)

In [71]:
print(df.columns)

Index(['district', 'state', 'child_stunting_rate', 'child_wasting_rate',
       'child_underweight_rate', 'child_anemia_rate', 'women_anemia_rate',
       'child_diarrhea_rate', 'child_ari_rate', 'safe_drinking_water_access',
       'sanitation_access', 'electricity_access', 'clean_cooking_fuel_access',
       'iodized_salt_usage', 'institutional_delivery_rate',
       'full_immunization_rate', 'health_insurance_coverage',
       'tobacco_use_women', 'tobacco_use_men', 'alcohol_use_women',
       'alcohol_use_men', 'high_blood_sugar_women', 'high_blood_sugar_men',
       'high_blood_pressure_women', 'high_blood_pressure_men',
       'female_education_rate'],
      dtype='object')

In [72]:
df

,district,state,child_stunting_rate,child_wasting_rate,child_underweight_rate,child_anemia_rate,women_anemia_rate,child_diarrhea_rate,child_ari_rate,safe_drinking_water_access,sanitation_access,electricity_access,clean_cooking_fuel_access,iodized_salt_usage,institutional_delivery_rate,full_immunization_rate,health_insurance_coverage,tobacco_use_women,tobacco_use_men,alcohol_use_women,alcohol_use_men,high_blood_sugar_women,high_blood_sugar_men,high_blood_pressure_women,high_blood_pressure_men,female_education_rate
0,nicobars,andaman and nicobar islands,21.6,15.7,24.6,37.7,38.3,5.7,1.8,98.8,83.5,97.9,56.9,99.4,97.8,(64.2),2.7,63.5,76.8,29.6,64.5,13.1,15.4,35.4,47.0,78.0
1,north and middle andaman,andaman and nicobar islands,27.0,27.0,42.8,30.4,62.1,4.5,7.0,92.2,86.4,93.2,61.3,99.9,97.7,*,2.1,46.8,70.5,5.1,45.3,16.7,18.3,27.4,32.2,82.7
2,south andaman,andaman and nicobar islands,21.1,12.6,17.4,43.4,57.7,6.0,0.0,97.9,89.3,99.6,91.9,99.7,99.5,(76.3),1.2,19.6,50.8,1.7,32.8,18.4,18.1,23.0,26.9,84.7
3,srikakulam,andhra pradesh,19.7,19.5,21.4,59.6,62.6,11.9,1.3,87.7,71.6,99.9,74.7,76.5,97.9,(82.8),75.6,7.1,21.3,0.6,28.3,17.4,17.6,22.1,22.9,60.0
4,vizianagaram,andhra pradesh,36.4,19.2,32.2,66.7,64.0,7.5,1.4,93.1,61.7,99.5,60.3,85.0,99.0,(76.8),76.7,11.4,21.5,0.8,32.3,14.3,14.5,25.2,25.1,56.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
702,south 24 parganas,west bengal,36.7,21.2,32.2,70.4,61.6,4.5,1.6,100.0,70.1,99.2,36.2,94.1,91.0,91.7,36.7,6.3,49.8,0.4,16.5,16.5,21.3,21.5,19.1,80.9
703,paschim medinipur,west bengal,31.1,30.3,40.0,66.0,81.5,6.3,1.4,95.5,58.3,95.4,17.5,93.8,87.6,76.9,25.8,18.8,50.5,1.5,20.8,17.9,21.7,19.3,19.0,72.1
704,purba medinipur,west bengal,25.8,15.5,30.6,67.5,70.4,8.9,3.8,87.8,69.8,99.0,17.0,90.0,91.5,88.4,21.5,12.9,40.1,2.0,14.8,21.3,24.0,18.1,21.3,83.0
705,paschim bardhaman,west bengal,39.7,25.5,41.0,74.7,65.8,8.8,2.0,95.2,71.5,97.0,56.3,89.8,89.8,62.4,21.8,11.8,40.2,0.8,14.6,16.2,23.4,17.6,20.7,74.8
706,purba bardhaman,west bengal,32.7,21.1,31.6,71.5,77.9,3.3,5.0,99.1,64.2,96.8,32.1,95.2,96.0,97.2,37.2,9.9,50.1,1.2,22.9,16.6,21.8,21.2,18.4,71.2

In [73]:
df.to_csv("nfhs_clean_final.csv", index=False)

#cleaning this dataset

In [74]:
df.columns = df.columns.str.strip().str.lower()
df.columns = df.columns.str.replace(' ', '_')

In [75]:
import numpy as np

# Replace problematic values
df.replace({'\*': np.nan, '\(': '', '\)': ''}, regex=True, inplace=True)

<>:4: SyntaxWarning: invalid escape sequence '\*'
<>:4: SyntaxWarning: invalid escape sequence '\('
<>:4: SyntaxWarning: invalid escape sequence '\)'
<>:4: SyntaxWarning: invalid escape sequence '\*'
<>:4: SyntaxWarning: invalid escape sequence '\('
<>:4: SyntaxWarning: invalid escape sequence '\)'
/tmp/ipykernel_14541/3921653840.py:4: SyntaxWarning: invalid escape sequence '\*'
  df.replace({'\*': np.nan, '\(': '', '\)': ''}, regex=True, inplace=True)
/tmp/ipykernel_14541/3921653840.py:4: SyntaxWarning: invalid escape sequence '\('
  df.replace({'\*': np.nan, '\(': '', '\)': ''}, regex=True, inplace=True)
/tmp/ipykernel_14541/3921653840.py:4: SyntaxWarning: invalid escape sequence '\)'
  df.replace({'\*': np.nan, '\(': '', '\)': ''}, regex=True, inplace=True)

In [76]:
for col in df.columns:
    if col not in ['district', 'state']:
        df[col] = pd.to_numeric(df[col], errors='coerce')

In [77]:
df.isnull().sum()

district                        0
state                           0
child_stunting_rate             0
child_wasting_rate              0
child_underweight_rate          0
child_anemia_rate               0
women_anemia_rate               0
child_diarrhea_rate             0
child_ari_rate                  0
safe_drinking_water_access      0
sanitation_access               0
electricity_access              0
clean_cooking_fuel_access       0
iodized_salt_usage              0
institutional_delivery_rate     0
full_immunization_rate         13
health_insurance_coverage       0
tobacco_use_women               0
tobacco_use_men                 0
alcohol_use_women               0
alcohol_use_men                 0
high_blood_sugar_women          0
high_blood_sugar_men            0
high_blood_pressure_women       0
high_blood_pressure_men         0
female_education_rate           0
dtype: int64

In [78]:
df.fillna(df.median(numeric_only=True), inplace=True)

In [79]:
df.dropna(inplace=True)

In [80]:
df.duplicated().sum()

np.int64(0)

In [81]:
df.drop_duplicates(inplace=True)

In [82]:
df['district'] = df['district'].str.strip().str.lower()
df['state'] = df['state'].str.strip().str.lower()

In [83]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 707 entries, 0 to 706
Data columns (total 26 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   district                     707 non-null    object
 1   state                        707 non-null    object
 2   child_stunting_rate          707 non-null    float64
 3   child_wasting_rate           707 non-null    float64
 4   child_underweight_rate       707 non-null    float64
 5   child_anemia_rate            707 non-null    float64
 6   women_anemia_rate            707 non-null    float64
 7   child_diarrhea_rate          707 non-null    float64
 8   child_ari_rate               707 non-null    float64
 9   safe_drinking_water_access   707 non-null    float64
 10  sanitation_access            707 non-null    float64
 11  electricity_access           707 non-null    float64
 12  clean_cooking_fuel_access    707 non-null    float64
 13  iodized_salt_usage           707 non-null    float64
 14  institutional_delivery_rate  707 non-null    float64
 15  full_immunization_rate       707 non-null    float64
 16  health_insurance_coverage    707 non-null    float64
 17  tobacco_use_women            707 non-null    float64
 18  tobacco_use_men              707 non-null    float64
 19  alcohol_use_women            707 non-null    float64
 20  alcohol_use_men              707 non-null    float64
 21  high_blood_sugar_women       707 non-null    float64
 22  high_blood_sugar_men         707 non-null    float64
 23  high_blood_pressure_women    707 non-null    float64
 24  high_blood_pressure_men      707 non-null    float64
 25  female_education_rate        707 non-null    float64
dtypes: float64(24), object(2)
memory usage: 143.7+ KB

In [84]:
df.describe()

,child_stunting_rate,child_wasting_rate,child_underweight_rate,child_anemia_rate,women_anemia_rate,child_diarrhea_rate,child_ari_rate,safe_drinking_water_access,sanitation_access,electricity_access,clean_cooking_fuel_access,iodized_salt_usage,institutional_delivery_rate,full_immunization_rate,health_insurance_coverage,tobacco_use_women,tobacco_use_men,alcohol_use_women,alcohol_use_men,high_blood_sugar_women,high_blood_sugar_men,high_blood_pressure_women,high_blood_pressure_men,female_education_rate
count,707.000000,707.000000,707.000000,707.000000,707.000000,707.000000,707.000000,707.000000,707.000000,707.000000,707.000000,707.000000,707.000000,707.000000,707.000000,707.000000,707.000000,707.000000,707.000000,707.000000,707.000000,707.000000,707.000000,707.000000
mean,33.506506,18.559264,29.524894,65.821782,55.948373,6.471853,2.542291,93.730552,71.921216,97.001414,54.091938,95.129703,88.675389,77.710467,40.224894,11.619802,40.605375,2.919943,23.194767,12.467468,14.732249,21.406506,24.765771,71.514003
std,8.460084,6.498809,9.707463,12.076166,11.966162,4.095010,2.061342,8.714380,14.283819,4.351601,24.179034,5.479412,12.002094,11.987258,23.060242,11.941824,14.081733,6.079831,13.363666,4.621944,4.951691,5.213090,6.766612,10.312555
min,13.200000,4.500000,7.200000,24.900000,14.900000,0.000000,0.000000,41.200000,29.200000,68.400000,8.600000,47.900000,21.400000,38.300000,1.200000,0.100000,6.800000,0.000000,0.100000,4.100000,4.800000,8.500000,10.000000,45.400000
25%,27.300000,13.900000,22.100000,59.500000,49.250000,3.700000,0.900000,92.000000,62.000000,96.400000,33.950000,93.800000,83.700000,70.050000,20.300000,4.100000,30.400000,0.300000,13.600000,9.000000,11.100000,17.600000,19.800000,64.400000
50%,32.800000,18.100000,29.400000,67.700000,57.200000,5.500000,2.100000,97.000000,73.700000,98.700000,50.400000,97.000000,92.200000,78.100000,35.700000,7.700000,42.500000,0.500000,20.200000,11.700000,14.100000,21.000000,24.400000,71.300000
75%,39.200000,22.800000,36.250000,74.000000,63.650000,8.700000,3.800000,99.300000,83.300000,99.500000,75.150000,98.600000,97.400000,87.000000,59.950000,14.800000,50.950000,1.700000,30.900000,15.300000,17.650000,24.500000,29.000000,78.950000
max,60.600000,48.000000,62.400000,95.500000,93.500000,39.300000,11.200000,100.000000,99.900000,100.000000,99.800000,100.000000,100.000000,100.000000,97.800000,70.600000,80.600000,42.800000,68.400000,32.100000,36.200000,42.100000,49.600000,99.200000

In [85]:
for col in df.select_dtypes(include=['float64']).columns:
    q1 = df[col].quantile(0.25)
    q3 = df[col].quantile(0.75)
    iqr = q3 - q1

    lower = q1 - 1.5 * iqr
    upper = q3 + 1.5 * iqr

    df[col] = df[col].clip(lower, upper)

In [86]:
df

,district,state,child_stunting_rate,child_wasting_rate,child_underweight_rate,child_anemia_rate,women_anemia_rate,child_diarrhea_rate,child_ari_rate,safe_drinking_water_access,sanitation_access,electricity_access,clean_cooking_fuel_access,iodized_salt_usage,institutional_delivery_rate,full_immunization_rate,health_insurance_coverage,tobacco_use_women,tobacco_use_men,alcohol_use_women,alcohol_use_men,high_blood_sugar_women,high_blood_sugar_men,high_blood_pressure_women,high_blood_pressure_men,female_education_rate
0,nicobars,andaman and nicobar islands,21.6,15.7,24.6,37.75,38.3,5.7,1.8,98.8,83.5,97.9,56.9,99.4,97.8,64.2,2.7,30.85,76.8,3.8,56.85,13.1,15.4,34.85,42.8,78.0
1,north and middle andaman,andaman and nicobar islands,27.0,27.0,42.8,37.75,62.1,4.5,7.0,92.2,86.4,93.2,61.3,99.9,97.7,78.1,2.1,30.85,70.5,3.8,45.30,16.7,18.3,27.40,32.2,82.7
2,south andaman,andaman and nicobar islands,21.1,12.6,17.4,43.40,57.7,6.0,0.0,97.9,89.3,99.6,91.9,99.7,99.5,76.3,1.2,19.60,50.8,1.7,32.80,18.4,18.1,23.00,26.9,84.7
3,srikakulam,andhra pradesh,19.7,19.5,21.4,59.60,62.6,11.9,1.3,87.7,71.6,99.9,74.7,86.6,97.9,82.8,75.6,7.10,21.3,0.6,28.30,17.4,17.6,22.10,22.9,60.0
4,vizianagaram,andhra pradesh,36.4,19.2,32.2,66.70,64.0,7.5,1.4,93.1,61.7,99.5,60.3,86.6,99.0,76.8,76.7,11.40,21.5,0.8,32.30,14.3,14.5,25.20,25.1,56.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
702,south 24 parganas,west bengal,36.7,21.2,32.2,70.40,61.6,4.5,1.6,100.0,70.1,99.2,36.2,94.1,91.0,91.7,36.7,6.30,49.8,0.4,16.50,16.5,21.3,21.50,19.1,80.9
703,paschim medinipur,west bengal,31.1,30.3,40.0,66.00,81.5,6.3,1.4,95.5,58.3,95.4,17.5,93.8,87.6,76.9,25.8,18.80,50.5,1.5,20.80,17.9,21.7,19.30,19.0,72.1
704,purba medinipur,west bengal,25.8,15.5,30.6,67.50,70.4,8.9,3.8,87.8,69.8,99.0,17.0,90.0,91.5,88.4,21.5,12.90,40.1,2.0,14.80,21.3,24.0,18.10,21.3,83.0
705,paschim bardhaman,west bengal,39.7,25.5,41.0,74.70,65.8,8.8,2.0,95.2,71.5,97.0,56.3,89.8,89.8,62.4,21.8,11.80,40.2,0.8,14.60,16.2,23.4,17.60,20.7,74.8
706,purba bardhaman,west bengal,32.7,21.1,31.6,71.50,77.9,3.3,5.0,99.1,64.2,96.8,32.1,95.2,96.0,97.2,37.2,9.90,50.1,1.2,22.90,16.6,21.8,21.20,18.4,71.2

In [87]:
df.isnull().sum()

district                       0
state                          0
child_stunting_rate            0
child_wasting_rate             0
child_underweight_rate         0
child_anemia_rate              0
women_anemia_rate              0
child_diarrhea_rate            0
child_ari_rate                 0
safe_drinking_water_access     0
sanitation_access              0
electricity_access             0
clean_cooking_fuel_access      0
iodized_salt_usage             0
institutional_delivery_rate    0
full_immunization_rate         0
health_insurance_coverage      0
tobacco_use_women              0
tobacco_use_men                0
alcohol_use_women              0
alcohol_use_men                0
high_blood_sugar_women         0
high_blood_sugar_men           0
high_blood_pressure_women      0
high_blood_pressure_men        0
female_education_rate          0
dtype: int64

In [88]:
df.to_csv("nfhs_clean_dataset1.csv", index=False)

#feature Engineering

In [89]:
df['overall_child_health_risk_score'] = (
    0.25 * df['child_stunting_rate'] +
    0.15 * df['child_wasting_rate'] +
    0.15 * df['child_underweight_rate'] +
    0.15 * df['child_anemia_rate'] +
    0.10 * df['women_anemia_rate'] +
    0.10 * df['child_diarrhea_rate'] +
    0.10 * df['child_ari_rate']
)

In [90]:
df['basic_infrastructure_risk_score'] = (
    (1 - df['safe_drinking_water_access']) +
    (1 - df['sanitation_access']) +
    (1 - df['clean_cooking_fuel_access'])
) / 3

In [91]:
df['lifestyle_disease_risk_score'] = (
    df['tobacco_use_men'] +
    df['tobacco_use_women'] +
    df['alcohol_use_men'] +
    df['alcohol_use_women']
) / 4

NCD Risk (Chronic Disease Risk)

In [92]:
df['chronic_disease_risk_score'] = (
    df['high_blood_sugar_men'] +
    df['high_blood_sugar_women'] +
    df['high_blood_pressure_men'] +
    df['high_blood_pressure_women']
) / 4

In [93]:
df['healthcare_accessibility_score'] = (
    df['institutional_delivery_rate'] +
    df['full_immunization_rate'] +
    df['health_insurance_coverage']
) / 3

In [95]:
df['district_overall_health_risk_score'] = (
    0.4 * df['overall_child_health_risk_score'] +
    0.2 * df['basic_infrastructure_risk_score'] +
    0.2 * df['lifestyle_disease_risk_score'] +
    0.2 * df['chronic_disease_risk_score']
)

In [96]:
def district_risk_level(score):
    if score < 0.3:
        return "Low"
    elif score < 0.6:
        return "Medium"
    else:
        return "High"

df['district_risk_level'] = df['district_overall_health_risk_score'].apply(district_risk_level)

In [97]:
df['district_health_risk_rank'] = df['district_overall_health_risk_score'].rank(ascending=False)

In [98]:
def identified_health_risk_factors(row):
    causes = []

    if row['safe_drinking_water_access'] < 0.5:
        causes.append("Poor drinking water")

    if row['sanitation_access'] < 0.5:
        causes.append("Poor sanitation")

    if row['child_stunting_rate'] > 0.4:
        causes.append("High malnutrition")

    if row['child_anemia_rate'] > 0.4:
        causes.append("High anemia")

    if row['clean_cooking_fuel_access'] < 0.5:
        causes.append("Indoor air pollution")

    if row['tobacco_use_men'] > 0.3:
        causes.append("High tobacco usage")

    return causes

df['identified_health_risk_factors'] = df.apply(identified_health_risk_factors, axis=1)

In [99]:
df

,district,state,child_stunting_rate,child_wasting_rate,child_underweight_rate,child_anemia_rate,women_anemia_rate,child_diarrhea_rate,child_ari_rate,safe_drinking_water_access,sanitation_access,electricity_access,clean_cooking_fuel_access,iodized_salt_usage,institutional_delivery_rate,full_immunization_rate,health_insurance_coverage,tobacco_use_women,tobacco_use_men,alcohol_use_women,alcohol_use_men,high_blood_sugar_women,high_blood_sugar_men,high_blood_pressure_women,high_blood_pressure_men,female_education_rate,overall_child_health_risk_score,basic_infrastructure_risk_score,lifestyle_disease_risk_score,chronic_disease_risk_score,healthcare_accessibility_score,district_overall_health_risk_score,district_risk_level,district_health_risk_rank,identified_health_risk_factors
0,nicobars,andaman and nicobar islands,21.6,15.7,24.6,37.75,38.3,5.7,1.8,98.8,83.5,97.9,56.9,99.4,97.8,64.2,2.7,30.85,76.8,3.8,56.85,13.1,15.4,34.85,42.8,78.0,21.6875,-78.733333,42.0750,26.5375,54.900000,6.650833,High,287.0,"[High malnutrition, High anemia, High tobacco usage]"
1,north and middle andaman,andaman and nicobar islands,27.0,27.0,42.8,37.75,62.1,4.5,7.0,92.2,86.4,93.2,61.3,99.9,97.7,78.1,2.1,30.85,70.5,3.8,45.30,16.7,18.3,27.40,32.2,82.7,30.2425,-78.966667,37.6125,23.6500,59.300000,8.556167,High,184.0,"[High malnutrition, High anemia, High tobacco usage]"
2,south andaman,andaman and nicobar islands,21.1,12.6,17.4,43.40,57.7,6.0,0.0,97.9,89.3,99.6,91.9,99.7,99.5,76.3,1.2,19.60,50.8,1.7,32.80,18.4,18.1,23.00,26.9,84.7,22.6550,-92.033333,26.2250,21.6000,59.000000,0.220333,Low,633.0,"[High malnutrition, High anemia, High tobacco usage]"
3,srikakulam,andhra pradesh,19.7,19.5,21.4,59.60,62.6,11.9,1.3,87.7,71.6,99.9,74.7,86.6,97.9,82.8,75.6,7.10,21.3,0.6,28.30,17.4,17.6,22.10,22.9,60.0,27.5800,-77.000000,14.3250,20.0000,85.433333,2.497000,High,530.0,"[High malnutrition, High anemia, High tobacco usage]"
4,vizianagaram,andhra pradesh,36.4,19.2,32.2,66.70,64.0,7.5,1.4,93.1,61.7,99.5,60.3,86.6,99.0,76.8,76.7,11.40,21.5,0.8,32.30,14.3,14.5,25.20,25.1,56.0,34.1050,-70.700000,16.5000,19.7750,84.166667,6.757000,High,281.0,"[High malnutrition, High anemia, High tobacco usage]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
702,south 24 parganas,west bengal,36.7,21.2,32.2,70.40,61.6,4.5,1.6,100.0,70.1,99.2,36.2,94.1,91.0,91.7,36.7,6.30,49.8,0.4,16.50,16.5,21.3,21.50,19.1,80.9,34.5150,-67.766667,18.2500,19.6000,73.133333,7.822667,High,219.0,"[High malnutrition, High anemia, High tobacco usage]"
703,paschim medinipur,west bengal,31.1,30.3,40.0,66.00,81.5,6.3,1.4,95.5,58.3,95.4,17.5,93.8,87.6,76.9,25.8,18.80,50.5,1.5,20.80,17.9,21.7,19.30,19.0,72.1,37.1400,-56.100000,22.9000,19.4750,63.433333,12.111000,High,52.0,"[High malnutrition, High anemia, High tobacco usage]"
704,purba medinipur,west bengal,25.8,15.5,30.6,67.50,70.4,8.9,3.8,87.8,69.8,99.0,17.0,90.0,91.5,88.4,21.5,12.90,40.1,2.0,14.80,21.3,24.0,18.10,21.3,83.0,31.8000,-57.200000,17.4500,21.1750,67.133333,9.005000,High,165.0,"[High malnutrition, High anemia, High tobacco usage]"
705,paschim bardhaman,west bengal,39.7,25.5,41.0,74.70,65.8,8.8,2.0,95.2,71.5,97.0,56.3,89.8,89.8,62.4,21.8,11.80,40.2,0.8,14.60,16.2,23.4,17.60,20.7,74.8,38.7650,-73.333333,16.8500,19.4750,58.000000,8.104333,High,210.5,"[High malnutrition, High anemia, High tobacco usage]"
706,purba bardhaman,west bengal,32.7,21.1,31.6,71.50,77.9,3.3,5.0,99.1,64.2,96.8,32.1,95.2,96.0,97.2,37.2,9.90,50.1,1.2,22.90,16.6,21.8,21.20,18.4,71.2,35.4250,-64.133333,21.0250,19.5000,76.800000,9.448333,High,141.0,"[High malnutrition, High anemia, High tobacco usage]"

In [100]:
df.to_csv("nfhs_ML_Pipeline_dataset.csv", index=False)

In [102]:
df["district"].unique()

array(['nicobars', 'north and middle andaman', 'south andaman',
       'srikakulam', 'vizianagaram', 'visakhapatnam', 'east godavari',
       'west godavari', 'krishna', 'guntur', 'prakasam', 'nellore',
       'ysr kadapa', 'kurnool', 'anantapur', 'chittoor', 'tawang',
       'west kameng', 'east kameng', 'papum pare', 'upper subansiri',
       'upper siang', 'changlang', 'lower subansiri', 'dibang valley',
       'lower dibang valley', 'anjaw', 'east siang', 'kra daadi',
       'kurung kumey', 'lohit', 'longding', 'namsai', 'siang', 'tirap',
       'west siang', 'kokrajhar', 'goalpara', 'barpeta', 'marigaon',
       'lakhimpur', 'dhemaji', 'tinsukia', 'dibrugarh', 'golaghat',
       'dima hasao', 'cachar', 'karimganj', 'hailakandi', 'bongaigaon',
       'chirang', 'kamrup', 'kamrup metropolitan', 'nalbari', 'baksa',
       'darrang', 'udalguri', 'biswanath', 'charaideo', 'dhubri', 'hojai',
       'jorhat', 'karbi anglong', 'majuli', 'nagaon', 'sivasagar',
       'sonitpur', 'south salmara mancachar', 'west karbi anglong',
       'west champaran', 'east champaran', 'sheohar', 'sitamarhi',
       'madhubani', 'supaul', 'araria', 'kishanganj', 'purnia', 'katihar',
       'madhepura', 'saharsa', 'darbhanga', 'muzaffarpur', 'gopalganj',
       'siwan', 'saran', 'vaishali', 'samastipur', 'begusarai',
       'khagaria', 'bhagalpur', 'banka', 'munger', 'lakhisarai',
       'sheikhpura', 'nalanda', 'patna', 'bhojpur', 'buxar',
       'kaimur bhabua', 'rohtas', 'aurangabad', 'gaya', 'nawada', 'jamui',
       'jehanabad', 'arwal', 'chandigarh', 'koriya', 'jashpur', 'raigarh',
       'korba', 'janjgir champa', 'kabeerdham', 'rajnandgaon',
       'mahasamund', 'dhamtari', 'uttar bastar kanker', 'narayanpur',
       'bijapur', 'balod', 'baloda bazar', 'balrampur', 'bastar',
       'bemetara', 'bilaspur', 'dantewada', 'durg', 'gariyaband',
       'kondagaon', 'mungeli', 'raipur', 'sukma', 'surajpur', 'surguja',
       'diu', 'daman', 'dadra and nagar haveli', 'north goa', 'south goa',
       'kachchh', 'banas kantha', 'patan', 'mahesana', 'gandhinagar',
       'porbandar', 'amreli', 'anand', 'dahod', 'narmada', 'bharuch',
       'the dangs', 'navsari', 'valsad', 'surat', 'tapi', 'ahmedabad',
       'arvalli', 'bhavnagar', 'botad', 'chhota udaipur',
       'devbhumi dwarka', 'gir somnath', 'jamnagar', 'junagadh', 'kheda',
       'mahisagar', 'morbi', 'panch mahals', 'rajkot', 'sabar kantha',
       'surendranagar', 'vadodara', 'panchkula', 'ambala', 'yamunanagar',
       'kurukshetra', 'kaithal', 'karnal', 'panipat', 'sonipat', 'jind',
       'fatehabad', 'sirsa', 'hisar', 'rohtak', 'jhajjar', 'mahendragarh',
       'rewari', 'gurgaon', 'mewat', 'faridabad', 'palwal', 'bhiwani',
       'charkhi dadri', 'chamba', 'kangra', 'lahaul and spiti', 'kullu',
       'mandi', 'hamirpur', 'una', 'solan', 'sirmaur', 'shimla',
       'kinnaur', 'kupwara', 'badgam', 'poonch', 'rajouri', 'kathua',
       'baramula', 'bandipore', 'srinagar', 'ganderbal', 'pulwama',
       'shopian', 'anantnag', 'kulgam', 'doda', 'ramban', 'kishtwar',
       'udhampur', 'reasi', 'jammu', 'samba', 'garhwa', 'chatra',
       'kodarma', 'giridih', 'deoghar', 'godda', 'sahibganj', 'pakur',
       'dhanbad', 'bokaro', 'lohardaga', 'purbi singhbhum', 'palamu',
       'latehar', 'hazaribagh', 'ramgarh', 'dumka', 'jamtara', 'ranchi',
       'khunti', 'gumla', 'simdega', 'pashchimi singhbhum',
       'saraikela kharsawan', 'belgaum', 'bagalkot', 'bidar', 'raichur',
       'koppal', 'gadag', 'dharwad', 'uttara kannada', 'haveri',
       'bellary', 'chitradurga', 'davanagere', 'shimoga', 'udupi',
       'chikmagalur', 'tumkur', 'bangalore urban', 'mandya', 'hassan',
       'dakshina kannada', 'kodagu', 'mysore', 'chamarajanagar',
       'gulbarga', 'yadgir', 'kolar', 'chikballapur', 'bangalore rural',
       'ramanagara', 'kasaragod', 'kannur', 'wayanad', 'kozhikkode',
       'malappuram', 'palakkad', 'thrissur', 'ernakulam', 'idukki',
       'kottayam', 'alappuzha', 'pathanamthitta', 'kollam',
       'thiruvananthapuram', 'leh', 'kargil', 'lakshadweep', 'sheopur',
       'morena', 'bhind', 'gwalior', 'datia', 'shivpuri', 'tikamgarh',
       'chhatarpur', 'panna', 'sagar', 'damoh', 'satna', 'rewa', 'umaria',
       'neemuch', 'mandsaur', 'ratlam', 'ujjain', 'dewas', 'dhar',
       'indore', 'khargone', 'barwani', 'rajgarh', 'vidisha', 'bhopal',
       'sehore', 'raisen', 'betul', 'harda', 'hoshangabad', 'katni',
       'jabalpur', 'narsinghpur', 'dindori', 'mandla', 'chhindwara',
       'seoni', 'balaghat', 'guna', 'ashoknagar', 'shahdol', 'anuppur',
       'sidhi', 'singrauli', 'jhabua', 'alirajpur', 'khandwa',
       'burhanpur', 'agar malwa', 'shajapur', 'nandurbar', 'dhule',
       'jalgaon', 'buldana', 'akola', 'washim', 'amravati', 'wardha',
       'nagpur', 'bhandara', 'gondiya', 'gadchiroli', 'chandrapur',
       'yavatmal', 'nanded', 'hingoli', 'parbhani', 'jalna', 'nashik',
       'mumbai suburban', 'mumbai', 'pune', 'ahmednagar', 'bid', 'latur',
       'osmanabad', 'solapur', 'satara', 'ratnagiri', 'sindhudurg',
       'kolhapur', 'sangli', 'palghar', 'thane', 'senapati', 'tamenglong',
       'churachandpur', 'bishnupur', 'thoubal', 'imphal west',
       'imphal east', 'ukhrul', 'chandel', 'south garo hills', 'ribhoi',
       'east khasi hills', 'east garo hills', 'east jantia hills',
       'north garo hills', 'south west garo hills',
       'south west khasi hills', 'west garo hills', 'west jaintia hills',
       'west khasi hills', 'mamit', 'kolasib', 'aizawl', 'champhai',
       'serchhip', 'lunglei', 'lawngtlai', 'mon', 'mokokchung',
       'zunheboto', 'wokha', 'dimapur', 'phek', 'tuensang', 'longleng',
       'kiphire', 'kohima', 'peren', 'central delhi', 'east delhi',
       'new delhi', 'north delhi', 'north east delhi', 'north west delhi',
       'shahdara', 'south delhi', 'south east delhi', 'south west delhi',
       'west delhi', 'bargarh', 'jharsuguda', 'sambalpur', 'debagarh',
       'sundargarh', 'kendujhar', 'mayurbhanj', 'baleshwar', 'bhadrak',
       'kendrapara', 'jagatsinghpur', 'cuttack', 'jajapur', 'dhenkanal',
       'anugul', 'nayagarh', 'khordha', 'puri', 'ganjam', 'gajapati',
       'kandhamal', 'baudh', 'subarnapur', 'balangir', 'nuapada',
       'kalahandi', 'rayagada', 'nabarangapur', 'koraput', 'malkangiri',
       'yanam', 'puducherry', 'mahe', 'karaikal', 'kapurthala',
       'jalandhar', 'hoshiarpur', 'shahid bhagat singh nagar',
       'fatehgarh sahib', 'ludhiana', 'moga', 'muktsar', 'faridkot',
       'bathinda', 'mansa', 'patiala', 'amritsar', 'tarn taran',
       'rupnagar', 'sahibzada ajit singh nagar', 'sangrur', 'barnala',
       'fazilka', 'firozpur', 'gurdaspur', 'pathankot', 'ganganagar',
       'hanumangarh', 'bikaner', 'churu', 'jhunjhunun', 'alwar',
       'bharatpur', 'dhaulpur', 'karauli', 'sawai madhopur', 'dausa',
       'jaipur', 'sikar', 'nagaur', 'jodhpur', 'jaisalmer', 'barmer',
       'jalor', 'sirohi', 'pali', 'ajmer', 'tonk', 'bundi', 'bhilwara',
       'rajsamand', 'dungarpur', 'banswara', 'chittaurgarh', 'kota',
       'baran', 'jhalawar', 'udaipur', 'pratapgarh', 'north', 'west',
       'south', 'east', 'thiruvallur', 'chennai', 'kancheepuram',
       'vellore', 'tiruvannamalai', 'viluppuram', 'salem', 'namakkal',
       'erode', 'nilgiris', 'dindigul', 'karur', 'tiruchirappalli',
       'perambalur', 'ariyalur', 'cuddalore', 'nagapattinam',
       'thiruvarur', 'thanjavur', 'pudukkottai', 'sivaganga', 'madurai',
       'theni', 'virudhunagar', 'ramanathapuram', 'thoothukudi',
       'tirunelveli', 'kanniyakumari', 'dharmapuri', 'krishnagiri',
       'coimbatore', 'tiruppur', 'adilabad', 'bhadradri kothagudem',
       'hyderabad', 'jagitial', 'jangoan', 'jayashankar bhupalapally',
       'jogulamba gadwal', 'kamareddy', 'karimnagar', 'khammam',
       'komaram bheem asifabad', 'mahabubabad', 'mahabubnagar',
       'mancherial', 'medak', 'medchal malkajgiri', 'nagarkurnool',
       'nalgonda', 'nirmal', 'nizamabad', 'peddapalli',
       'rajanna sircilla', 'ranga reddy', 'sangareddy', 'siddipet',
       'suryapet', 'vikarabad', 'wanaparthy', 'warangal rural',
       'warangal urban', 'yadadri bhuvanagiri', 'dhalai', 'gomati',
       'khowai', 'north tripura', 'sepahijala', 'south tripura',
       'unakoti', 'west tripura', 'saharanpur', 'bijnor', 'rampur',
       'jyotiba phule nagar', 'meerut', 'baghpat', 'gautam buddha nagar',
       'bulandshahr', 'aligarh', 'mahamaya nagar', 'mathura', 'agra',
       'firozabad', 'mainpuri', 'bareilly', 'pilibhit', 'shahjahanpur',
       'kheri', 'sitapur', 'hardoi', 'unnao', 'lucknow', 'farrukhabad',
       'kannauj', 'etawah', 'auraiya', 'kanpur dehat', 'kanpur nagar',
       'jalaun', 'jhansi', 'lalitpur', 'mahoba', 'banda', 'chitrakoot',
       'fatehpur', 'kaushambi', 'allahabad', 'barabanki', 'faizabad',
       'ambedkar nagar', 'bahraich', 'shrawasti', 'gonda',
       'siddharth nagar', 'basti', 'sant kabir nagar', 'mahrajganj',
       'gorakhpur', 'kushinagar', 'deoria', 'azamgarh', 'mau', 'ballia',
       'jaunpur', 'ghazipur', 'chandauli', 'varanasi', 'bhadohi',
       'mirzapur', 'sonbhadra', 'etah', 'kanshiram nagar', 'amethi',
       'budaun', 'ghaziabad', 'hapur', 'moradabad', 'muzaffarnagar',
       'rae bareli', 'sambhal', 'shamli', 'sultanpur', 'uttarkashi',
       'chamoli', 'rudraprayag', 'tehri garhwal', 'dehradun', 'garhwal',
       'pithoragarh', 'bageshwar', 'almora', 'champawat', 'nainital',
       'udham singh nagar', 'haridwar', 'darjiling', 'jalpaiguri',
       'cooch behar', 'uttar dinajpur', 'dakshin dinajpur', 'maldah',
       'murshidabad', 'birbhum', 'nadia', 'north 24 parganas', 'hugli',
       'bankura', 'puruliya', 'howrah', 'kolkata', 'south 24 parganas',
       'paschim medinipur', 'purba medinipur', 'paschim bardhaman',
       'purba bardhaman'], dtype=object)